### ISSUE TITLE
crash with java.lang.IndexOutOfBoundsException: getChars(),  has end before start

### ISSUE THREAD

**Issue by breezejin** [rockerhieu/emojicon#107]
i input 
┃  ┏┃┃┃┏┛
┃  ━┛━┛┏┛
 ━┛♡♡ ━┛
between two emoji icon, my code crashed, help me.

error log as below:

01-22 21:40:32.726: E/AndroidRuntime(2140): java.lang.IndexOutOfBoundsException: getChars (23 ... 13) has end before start
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1009)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:913)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.TextUtils.getChars(TextUtils.java:79)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.MeasuredText.setPara(MeasuredText.java:106)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.StaticLayout.generate(StaticLayout.java:477)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.DynamicLayout.reflow(DynamicLayout.java:284)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.DynamicLayout.access$000(DynamicLayout.java:35)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:644)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:673)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:999)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:567)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:500)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:435)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:675)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:279)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.os.Looper.loop(Looper.java:136)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at android.app.ActivityThread.main(ActivityThread.java:5133)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
01-22 21:40:32.726: E/AndroidRuntime(2140): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)

**Comment by breezejin** [comment]
Notice: you should input two emojiicon first, and then insert that string bewteen them, you can see the problem.
You can not input them one by one.
