### ISSUE TITLE
 Caused by: java.lang.NoClassDefFoundError: com.rockerhieu.emojicon.R$drawable

### ISSUE THREAD

**Issue by CodeBoyChd** [rockerhieu/emojicon#109]
My Application is crashing everytime when I call this function:
EmojiconHandler.addEmojis(getContext(), builder, mEmojiconSize, mEmojiconAlignment, mEmojiconTextSize, mTextStart, mTextLength, false);
           
This is happening in 4.4.2 version or may be also below 5, For more than 5 version this is working absolutely fine.
--------------------------------------------------------------
Caused by: java.lang.NoClassDefFoundError: com.rockerhieu.emojicon.R$drawable                                                              at com.rockerhieu.emojicon.EmojiconHandler.<clinit>(EmojiconHandler.java:38)
at com.xyz.abc.common.util.TextViewPlus.setText(TextViewPlus.java:95)
at android.widget.TextView.<init>(TextView.java:1339)
at android.widget.TextView.<init>(TextView.java:635)
-------------------------------------------------------------

TextViewPlus is my customized TextView.

**Comment by lastw0nd3r** [comment]
I am also facing the same issue. Can we have this sorted on priority? @rockerhieu @CodeBoyChd @daniele-athome @KTachibanaM
