### ISSUE TITLE
Save Instance State crashes for the new recent tap.

### ISSUE THREAD

**Issue by pY4x3g** [rockerhieu/emojicon#57]
I get the following error. I think this issue is related to
https://code.google.com/p/android/issues/detail?id=77285.
Perhaps i'll try to fix it by myself in a few days, but i wanted to share this bug.

java.lang.IllegalStateException: Fragment EmojiconRecentsGridFragment{44be12c0 id=0x7f060030} is not currently in the FragmentManager
	at android.support.v4.app.FragmentManagerImpl.putFragment(FragmentManager.java:571)
	at android.support.v4.app.FragmentStatePagerAdapter.saveState(FragmentStatePagerAdapter.java:188)
	at android.support.v4.view.ViewPager.onSaveInstanceState(ViewPager.java:1270)
	at android.view.View.dispatchSaveInstanceState(View.java:13570)
	at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2813)
	at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2819)
	at android.view.View.saveHierarchyState(View.java:13553)
	at android.support.v4.app.FragmentManagerImpl.saveFragmentViewState(FragmentManager.java:1629)
	at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1649)
	at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1710)
	at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:524)
	at android.app.Activity.performSaveInstanceState(Activity.java:1184)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1241)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3331)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3390)
	at android.app.ActivityThread.access$1100(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1279)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5335)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by pY4x3g** [comment]
Oh, after I submitted this issue I saw that there is already a patch for the support package.
So, perhaps this bug don't arise in a newer version of the support package. I'll give it a try and will give an update here.

**Comment by rockerhieu** [comment]
Cool, I will check it out.

**Comment by suraj9781** [comment]
Got the same crash:
STACK_TRACE=java.lang.IllegalStateException: Fragment EmojiconRecentsGridFragment{43d9f8e8 id=0x7f0d00de} is not currently in the FragmentManager
at android.support.v4.app.FragmentManagerImpl.putFragment(FragmentManager.java:573)
at android.support.v4.app.FragmentStatePagerAdapter.saveState(FragmentStatePagerAdapter.java:188)
at android.support.v4.view.ViewPager.onSaveInstanceState(ViewPager.java:1270)
at android.view.View.dispatchSaveInstanceState(View.java:12739)
at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2609)
at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:2615)
at android.view.View.saveHierarchyState(View.java:12722)
at android.support.v4.app.FragmentManagerImpl.saveFragmentViewState(FragmentManager.java:1639)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1023)
at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1233)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:709)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:456)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5047)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
at dalvik.system.NativeStart.main(Native Method)
