### ISSUE TITLE
Emojiicon fragments cannot be cast to android.app.Fragment

### ISSUE THREAD

**Issue by CHRehan** [rockerhieu/emojicon#72]
Caused by: java.lang.ClassCastException: com.rockerhieu.emojicon.EmojiconsFragment cannot be cast to android.app.Fragment
            at android.app.Fragment.instantiate(Fragment.java:577)
            at android.app.Fragment.instantiate(Fragment.java:552)
            at android.app.Activity.onCreateView(Activity.java:4656)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:256)
            at android.app.Activity.setContentView(Activity.java:1867)
            at com.example.rehan.emojiicon.MainActivity.onCreate(MainActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:5008)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by rockerhieu** [comment]
Please make sure you're importing `android.support.v4.app.Fragment` and not `android.app.Fragment`.

**Comment by CHRehan** [comment]
i am trying to hide or show the fragment using one button can you send me
the code of this work??

On Thu, Aug 27, 2015 at 9:30 AM, Hieu Rocker <notifications@github.com>
wrote:

> Closed #72 <https://github.com/rockerhieu/emojicon/issues/72>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rockerhieu/emojicon/issues/72#event-393622145>.
>



-- 


*Best Regards:REHAN .CH.*

*CELL #       +92_333_6933303*
